/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package minmax;

import java.awt.Color;
import minmax.model.Config;
import minmax.model.Surface;

/**
 *
 * @author Kouprianov Maxim <me@kc.vc> @ SE HSE
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();

        Surface surface = new Surface();

        Config a = new Config(2, 1);
        Config b = new Config(3, 4);
        Config c = new Config(8, 6);
        Config d = new Config(10, 11);
        Config e = b.star();
        Config f = new Config(14, 0);

        Config g = new Config();
        long start = System.currentTimeMillis();
        for(int i=0; i< 1; ++i){
          g = a.star().times(b.star()).times(c.star());
        }
        long end = System.currentTimeMillis();
        System.out.println((end-start) / 1.0);
        System.out.println(g.getVertexCount());

        surface.addLayer(g, Color.red);
        
        //surface.addLayer(new Config(0, -4).plus(new Config(5, -4)).plus(new Config(3, -2)).plus(new Config(8, -2)), Color.green);
        //ystem.out.println((a.plus(b)).star().plus(c));
        //surface.addLayer(a.plus(b).plus(c).plus(d), Color.blue);
        //surface.addLayer(a.plus(b).plus(c).plus(d), Color.green);
//        
//        Config lol = new Config(0, 0);
//        for(int i = 1; i< 20000; i += 1)
//        {
//            lol = lol.plus(new Config(i, i));
//            
//        }
//        
//        surface.addLayer(lol, Color.red, false);
//        
//        Config blue = new Config(3, 3);
//        for(int i = 2; i< 20000; i += 2)
//        {
//            blue = blue.plus(new Config(i, i));
//            
//        }
//        
//        surface.addLayer(blue, Color.blue, false);

        plotter1.setSurface(surface);
        plotter1.setXLabel("\\delta");
        plotter1.setYLabel("t");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plotter1 = new minmax.gui.Plotter();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plotter1.setXLabel("\\gamma");
        plotter1.setYLabel("\\delta");

        org.jdesktop.layout.GroupLayout plotter1Layout = new org.jdesktop.layout.GroupLayout(plotter1);
        plotter1.setLayout(plotter1Layout);
        plotter1Layout.setHorizontalGroup(
            plotter1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );
        plotter1Layout.setVerticalGroup(
            plotter1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 288, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(plotter1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(plotter1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private minmax.gui.Plotter plotter1;
    // End of variables declaration//GEN-END:variables
}
